### PR TITLE
fix: Textarea::perform returns CmdResult::Changed on state change

### LINKED ISSUE #179: [BUG] - `Textarea::perform` will always return `CmdResult::None`
## Description

I have noticed that `Textarea::perform` will always report `CmdResult::None` instead of something like `CmdResult::Changed(State::One(StateValue::Usize(self.states.list_index)))`

https://github.com/veeso/tui-realm-stdlib/blob/2e1ceb3aedd1d0b6d95b8ce4e1b380876a6c60f2/src/components/textarea.rs#L285-L318

## Steps to reproduce

Basically just look at the `Textarea::perform` code, though here is a basic overview (not runnable):

```rs
#[derive(MockComponent)]
pub struct Wrap {
    component: Textarea,
}

impl Wrap {
    pub fn new() -> Self {
        Self {
            component: Textarea::default().title("Hello", Alignment::Center),
        }
    }
}

#[derive(Debug, PartialEq)]
enum AMsg {}

impl Component<AMsg, NoUserEvent> for Wrap {
    fn on(&mut self, ev: Event<NoUserEvent>) -> Option<AMsg> {
        let res = self.perform(Cmd::Move(Direction::Down));
        debug!("Result: {:#?}", res);
        None
    }
}

fn somewhere(app: &mut Application<_>) {
    assert!(app
        .attr(
            &Id::Textarea,
            Attribute::Text,
            AttrValue::Payload(PropPayload::Vec(
                ["Hello", "There", "again"].into_iter().map(|v| TextSpan::new(v)).map(PropValue::TextSpan).collect()
            ))
        )
        .is_ok());
}
```

## Expected behaviour

`Textarea::perform` to not report `CmdResult::None` if it has performed something

## Environment

- OS: Linux
- Architecture x86_64
- Rust version: 1.84.0
- tui-realm version: 2.0.3
- tui-realm-std version: 2.0.1

### PR DESCRIPTION
**Pull request by veeso**
## Summary

- **stdlib Textarea** (read-only): `state()` now returns `State::Single(StateValue::Usize(list_index))` instead of `State::None`; `perform()` returns `CmdResult::Changed` when the scroll index moves
- **editable TextArea**: `perform()` returns `CmdResult::Changed` when text content is modified (typing, deleting, undo/redo, paste, etc.)
- Both components still return `CmdResult::None` when an operation has no effect (e.g., scrolling at boundary)

## Test plan

- [x] stdlib textarea unit tests updated and passing
- [x] editable textarea tests passing
- [x] clippy clean

Closes #179

### CODE REVIEW

File: crates/tuirealm-textarea/src/lib.rs [hunk 1]
```diff
@@ -688,24 +665,27 @@ impl Component for TextArea<'_> {
...
-                CmdResult::None
             }
-            Cmd::Submit => CmdResult::Submit(self.state()),
-            _ => CmdResult::None,
+            Cmd::Submit => return CmdResult::Submit(self.state()),
+            _ => return CmdResult::None,
+        }
+        let current_lines: Vec<String> =
+            self.widget.lines().iter().map(|l| l.to_string()).collect();
+        if prev_lines != current_lines {
```
Comment (hasezoey) [inline crates/tuirealm-textarea/src/lib.rs]: This could be combined to avoid cloning strings and having another vector

**Review by hasezoey — CHANGES_REQUESTED** [review]
Looks mostly good to me, with a minor nitpick and consider adding tests.

**Review by hasezoey — APPROVED** [review]
